### ISSUE TITLE
Adding setPatchBank to patch_bank module

### ISSUE THREAD

**Issue by olmigs** [michgz/casio-registrations#3]
Howdy Mike,

I wondered if you could give me more context on setPatchName() method? I've been using the library to update Pan and Volume values without issue, yet when I'm using patch and bankMSB values in setPatchName(), the Patch Names are not updated.

I'm not seeing in the source code that setPatchName() does not mutate `self`, so I'm not sure if I'm misusing this function. If you'd like to see the library in action, check out [this repo](https://github.com/olmigs/flaskapp/blob/master/server.py).

**Comment by michgz** [comment]
Thanks for contacting directly. Chandler has already pointed out your repo to me so I'm aware of the progress you're making.

You're absolutely right that setPatchBank was broken, corrected now in v1.4. It's not documented in the Readme, but if you're already using it you'll already have figured it out.
